insert into actors(FIO) values ('Roman Flew Kombat'),
('Prokofiewa Kira Ignatieva'),
('Avdeeva Dola Artemovna'),
('Romanova Nora Vladislavovna'),
('Strelkova Kamilla Parfenevna'),
('Muhina Larisa Bogdanova'),
('Subbotina Zinaida Leonidiwna'),
('Kornilova Adelia Evgenievna'),
('Vlasova Elga Frolova'),
('Ivankova Svyatoslava Timofeevna'),
('Denisova Magdalina Onisimovna'),
('Suhanov Ivan Melsovich'),
('Ignatiev Velor Sozonovich'),
('Voroncov Artur Stanislavovich'),
('Bobrov Villi Tarasovich'),
('Safonov Gordey Eldarovich'),
('Bragin Artem Yakovlevich'),
('Fedoseev Yuriy Timurovich'),
('Ustinov Isak Romanovich');

insert into authors(FIO) values ('Roman Hy Kombat'),
('Prokofiewa Kira Gi'),
('Avdeeva Dola Gomaln'),
(' Flotsi Nora Vladislavovna');

Insert into industry(name) values ('Homa'),
('Hutao'),
('Ganuy'),
('Ellegy'),
('Kozooha'),
('EndLess'),
('Monoliza'),
('Morganna'),
('RDN'),
('Gobazol'),
('Bionicle'),
('Baal'),
('Naraka'),
('BlueArchive'),
('FluteLess'),
('Deadend'),
('Aromotization'),
('OfficeParty'),
('ConfluenceReduction'),
('InstendlyRT');
Insert into command(name) values ('Raws1'),
('Raws3'),
('Raws2'),
('Made In Abbys'),
('No game'),
('No life'),
('Ruine Guardian');

insert into premies(name_fest, year_completed) values ('Grand fest bads films1','2002'),
('Grand fest best film3', '2003'),
('Creative fest','2004'),
('FESTIVAL','2012');

insert into producers(FIO) values
('Prokofiewa Lima Romantieva'),
('Helga Dola Artemovna'),
('Romanova Flew Vladislavovna'),
('Strelkova Kamilla Grachova'),
('Muhina Larisa Montas');
